services:
  frontend:
    build:
      context: ./chess_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_BASE_URL=http://api:8000
    depends_on:
      - backend

  backend:
    build:
      context: ./chess_backend
      dockerfile: Dockerfile
    ports:
        - "8000:8000"
    volumes:
        - ../chess_backend:/app
    depends_on:
        - db
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: roi_db
        POSTGRES_HOST: db
        POSTGRES_PORT: 5432
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: roi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: