
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: roi_db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: roi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: